### ISSUE TITLE
intrinsic.to.map is not a function

### ISSUE THREAD

**Issue by bdashore3** [ricokahler/sanity-codegen#46]
Hi there, I attempted to generate types using this tool with the blog template schema from `sanity init` and I kept getting this error.

```
[kingbri@kingremote studio-test]$ npx sanity-codegen
TypeError: intrinsic.to.map is not a function
    at convertType (/home/kingbri/studio-test/node_modules/sanity-codegen/generate-types.js:109:34)
    at convertField (/home/kingbri/studio-test/node_modules/sanity-codegen/generate-types.js:180:33)
    at /home/kingbri/studio-test/node_modules/sanity-codegen/generate-types.js:204:31
    at Array.map (<anonymous>)
    at generateTypeForDocument (/home/kingbri/studio-test/node_modules/sanity-codegen/generate-types.js:204:18)
    at Array.map (<anonymous>)
    at generateTypes (/home/kingbri/studio-test/node_modules/sanity-codegen/generate-types.js:233:50)
    at cli (/home/kingbri/studio-test/node_modules/sanity-codegen/cli.js:75:51)
```

I believe this was because of one of the schemas provided (post.js). The schema is attached in [this document](https://del.dog/ecypizecer.txt) due to length.

If you have any idea as to why this happens, please let me know. Thanks!

**Comment by bdashore3** [comment]
Steps to reproduce
1. `sanity init`
2. Choose blog schema template
3. install sanity-codegen and prettier
4. create sanity-codegen.config.ts with `'./schemas/schema.js'` for schemaPath and `'./schemas/schema.ts'` for `outputPath`
5.  `npx sanity-codegen` or `yarn sanity-codegen`

**Comment by ricokahler** [comment]
I see that the issue is that the codegen expects all references to have the `to` prop be an array but that schema has it without an array.

Looking at [the current Sanity docs](https://www.sanity.io/docs/reference-type#to-be04ff05daec), it doesn't say it can accept a non-array so I didn't plan for it… but there it is, in the default example, staring me in the face lol.

It's an easy fix, I'll have it out soon.
