### ISSUE TITLE
getting a cannot find module 'sanity-codgen/schema-creator-shim' error

### ISSUE THREAD

**Issue by nirjan-dev** [ricokahler/sanity-codegen#92]
full error message when I run the sanity-codegen command

```
Error: Cannot find module 'sanity-codegen/schema-creator-shim'
Require stack:
- /home/nk13/work/universal-content/schemas/schema.js
- /home/nk13/work/manifold/packages/manifold-services/node_modules/sanity-codegen/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/nk13/work/universal-content/schemas/schema.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/home/nk13/work/manifold/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/home/nk13/work/manifold/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nk13/work/universal-content/schemas/schema.js',
    '/home/nk13/work/manifold/packages/manifold-services/node_modules/sanity-codegen/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/nk13/.local/share/nvm/v14.15.3/bin/node
Arguments: /home/nk13/.local/share/nvm/v14.15.3/lib/node_modules/yarn/lib/cli.js generate:types
Directory: /home/nk13/work/manifold/packages/manifold-services
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

my sanity codgen config file

```
import path from 'path'
import { SanityCodegenConfig } from 'sanity-codegen'

const config: SanityCodegenConfig = {
	schemaPath: path.resolve(
		__dirname,
		'../../../universal-content/schemas/schema.js'
	),
	outputPath: path.resolve(__dirname, './src/models/Schema.ts'),
	babelOptions: {
		ignore: [] // <-- this resets the ignore option (but makes codegen super slow)
	}
}

export default config

```

My schema.js file in the sanity project

```
// First, we must import the schema creator
import createSchema from "part:@sanity/base/schema-creator";

// Then import schema types from any plugins that might expose them
import schemaTypes from "all:part:@sanity/base/schema-type";

// Document Schemas
import author from "./documents/author";
import category from "./documents/category";
import article from "./documents/article";
import page from "./documents/page";

// import videoStream from "./documents/videoStream";
import siteSettings from "./documents/siteSettings";
import connatixVideoPlaylist from "./documents/connatixVideoPlaylist";
import connatixClickToPlayVideos from "./documents/connatixClickToPlayVideos";
import apesterPlaylist from "./documents/apesterPlaylist";
import inArticleAdvertisements from "./documents/inArticleAdvertisements";
import playspaceFeed from "./documents/playspaceFeed";

// Object Types
import bioPortableText from "./objects/bioPortableText";
import articlePortableText from "./objects/articlePortableText";
import articleReference from "./objects/articleReference";

// SEO
import articleSeo from "./objects/seo/articleSeo";

// Embeds
import twitter from "./objects/embeds/twitter";
import video from "./objects/embeds/video";
import instagram from "./objects/embeds/instagram";
import reddit from "./objects/embeds/reddit";
import twitchClip from "./objects/embeds/twitchClip";
import twitchStream from "./objects/embeds/twitchStream";
import facebook from "./objects/embeds/facebook";

import displayAd from "./objects/embeds/displayAd";
import ctpVideo from "./objects/embeds/ctpVideo";

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
  // We name our schema
  name: "default",
  // Then proceed to concatenate our document type
  // to the ones provided by any plugins that are installed
  types: schemaTypes.concat([
    // Document Schemas
    siteSettings,
    author,
    category,
    article,
    page,
    // videoStream,
    connatixVideoPlaylist,
    connatixClickToPlayVideos,
    apesterPlaylist,
    inArticleAdvertisements,
    playspaceFeed,

    // SEO Objects (We do this for re-usability and easy management of files)
    articleSeo,

    // Embeds
    twitter,
    video,
    instagram,
    reddit,
    twitchClip,
    twitchStream,
    facebook,
    displayAd,
    ctpVideo,

    // Object Types
    bioPortableText,
    articlePortableText,
    articleReference,
  ]),
});

```

Let me know if you need more details, I'm using v.0.9.1

**Comment by ricokahler** [comment]
I've re-written most of the babel setup in the [`alpha` branch if you'd like to check it out](https://github.com/ricokahler/sanity-codegen/tree/alpha/packages/cli). It may solve your issue here.
